version: "0.5"

x-depends-on: &depends_on
  apiserver:
    condition: process_healthy
x-availability: &availability
  restart: always

environment:
  - "LIMA_WORKDIR=$HOME"

processes:

  apiserver:
    command: "lima ./gokube/apiserver --address :${PORT}"
    environment:
      - "LIMA_INSTANCE=master"
    availability: *availability
    liveness_probe: &probe
      period_seconds: 5
      http_get:
        host: ${HOST}
        scheme: http
        path: "/api/v1/healthz"
        port: ${PORT}
    readiness_probe: *probe
    shutdown:
      command: "lima killall apiserver"

  controller:
    command: "lima ./gokube/controller"
    environment:
      - "LIMA_INSTANCE=master"
    depends_on: *depends_on
    availability: *availability
    shutdown:
      command: "lima killall controller"

  scheduler:
    command: "lima ./gokube/scheduler"
    environment:
      - "LIMA_INSTANCE=master"
    depends_on: *depends_on
    availability: *availability
    shutdown:
      command: "lima killall scheduler"

  worker1:
    command: "lima ./gokube/kubelet --node-name worker1 --api-server-url ${LIMA_MASTER_HOST}:${PORT}"
    environment:
      - "LIMA_INSTANCE=worker1"
    depends_on:
      apiserver:
        condition: process_healthy
    availability: *availability
    shutdown:
      command: "lima killall kubelet"

  worker1-dockerps:
    command: "lima docker ps"
    environment:
      - "LIMA_INSTANCE=worker1"
    availability:
      restart: always
      backoff_seconds: 3

  worker2:
    command: "lima ./gokube/kubelet --node-name worker2 --api-server-url ${LIMA_MASTER_HOST}:${PORT}"
    environment:
      - "LIMA_INSTANCE=worker2"
    depends_on:
      apiserver:
        condition: process_healthy
    availability: *availability
    shutdown:
      command: "lima killall kubelet"

  worker2-dockerps:
    command: "lima docker ps"
    environment:
      - "LIMA_INSTANCE=worker2"
    availability:
      restart: always
      backoff_seconds: 3
