name: CI/CD

on:
  push:
    branches: [ "main", "makefile" ]
    paths-ignore:
      - .gitignore
      - README.md
  pull_request:
    branches: [ "main", "makefile" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.5
      
      - run: go version
