name: CI/CD

on:
  push:
    paths-ignore:
      - .gitignore
      - README.md
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.5
            
      - name: Install dependencies
        run: make deps
      
      - name: Check fmt
        run: make fmt-check

      - name: Run vet
        run: make vet

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4
          args: "-v --exclude S1000"

      - name: Run all tests
        run: make test
