name: CI/CD

on:
  push:
    branches: [ "main", "makefile" ]
    paths-ignore:
      - .gitignore
      - README.md
  pull_request:
    branches: [ "main", "makefile" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.5
            
      - name: Install dependencies
        run: make deps
      
      - name: Check fmt
        run: make fmt-check

      - name: Run vet
        run: make vet

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4
          args: "-v --exclude S1000"

      - name: Run test/api
        run: make test/api

      - name: Run test/controller
        run: make test/controller

      - name: Run test/kubelet
        run: make test/kubelet

      - name: Run test/listwatch
        run: make test/listwatch

      - name: Run test/registry
        run: make test/registry

      - name: Run test/runtime
        run: make test/runtime

      - name: Run test/scheduler
        run: make test/scheduler

      - name: Run test/storage
        run: make test/storage
